# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' ngram generator
#'
#' @param x list of character vectors
#' @param n number of grams
#' @param n_min minimum number of grams
#' @param delim delimiter
#'
rcpp_ngram <- function(x, n, n_min, delim) {
    .Call(`_textrecipes_rcpp_ngram`, x, n, n_min, delim)
}

